name: Misspell fixer

on:
  - push

jobs:
  misspell-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sobolevn/misspell-fixer-action@master
    - name: Get branch name
      id: get_branch
      run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
    - uses: peter-evans/create-pull-request@v2
      with:
        commit-message: 'Fix typos by misspell-fixer'
        title: 'Fix typos by misspell-fixer'
        assignees: ${{ github.actor }}
        reviewers: ${{ github.actor }}
        branch: 'auto-pr/misspell-fixer/${{ steps.get_branch.outputs.branch }}'
